config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
name: 'netsuite_source'
version: '1.0.0'

models:
  netsuite_source:
    +materialized: view
    +schema: netsuite_source

vars:
  netsuite_source:
    accounts_pass_through_columns: []
    classes_pass_through_columns: []
    consolidated_exchange_rates_pass_through_columns: []
    customers_pass_through_columns: []
    departments_pass_through_columns: []
    employees_pass_through_columns: []
    items_pass_through_columns: []
    jobs_pass_through_columns: []
    locations_pass_through_columns: []
    subsidiaries_pass_through_columns: []
    time_entries_pass_through_columns: []
    transactions_pass_through_columns: []
    transaction_lines_pass_through_columns: []
    vendors_pass_through_columns: []

clean-targets:
- target
- dbt_modules
- dbt_packages
