name: 'netsuite_source_integration_tests'

version: '0.1.0'

profile: 'integration_tests'
config-version: 2
vars:
  netsuite_source:
    netsuite_schema: netsuite_source_integration_tests_1
    netsuite_data_model_override: netsuite
    netsuite_accounting_book_identifier: "netsuite2_accounting_book_data"
    netsuite_accounting_period_identifier: "netsuite2_accounting_period_data"
    netsuite_account_identifier: "netsuite2_account_data"
    netsuite_classification_identifier: "netsuite2_classification_data"
    netsuite_consolidated_exchange_rate_identifier: "netsuite2_consolidated_exchange_rate_data"
    netsuite_currency_identifier: "netsuite2_currency_data"
    netsuite_customer_identifier: "netsuite2_customer_data"
    netsuite_department_identifier: "netsuite2_department_data"
    netsuite_entity_identifier: "netsuite2_entities_data"
    netsuite_item_identifier: "netsuite2_item_data"
    netsuite_job_identifier: "netsuite2_job_data"
    netsuite_location_identifier: "netsuite2_location_data"
    netsuite_subsidiary_identifier: "netsuite2_subsidiary_data"
    netsuite_transaction_accounting_line_identifier: "netsuite2_tran_acct_line_data"
    netsuite_transaction_line_identifier: "netsuite2_transaction_line_data"
    netsuite_transaction_identifier: "netsuite2_transaction_data"
    netsuite_vendor_identifier: "netsuite2_vendor_data"
    netsuite_vendor_category_identifier: "netsuite2_vendor_category_data"
    netsuite_accounting_book_subsidiaries_identifier: "netsuite2_accounting_book_sub_data"
    netsuite_accounting_period_fiscal_calendars_identifier: "netsuite2_accounting_period_fiscal_cal_data"
    netsuite_account_type_identifier: "netsuite2_account_type_data"
    netsuite_entity_address_identifier: "netsuite2_entity_address_data"
    netsuite_location_main_address_identifier: "netsuite2_location_main_address_data"
seeds:
  +quote_columns: "{{ true if target.type in ('redshift','postgres') else false }}"
  netsuite_source_integration_tests:
    +column_types:
      ending: timestamp
      due_date: timestamp

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']