{{ config(enabled=(var('netsuite__advanced_revenue_management_enabled', false))) }}

with source as (
      select * from {{ var('netsuite_revenue_elements') }}
),
renamed as (
    select
        itemisautoexpand = 'T' as is_item_auto_expand,
        sourcerecordtype as source_record_type,
        accountingbook as accounting_book_id,
        cseg_paactivitycode as activity_code,
        allocatedcontractcostamount as allocated_contract_cost_amount,
        allocationtype as allocation_type_id,
        alternatequantity as alternate_quantity,
        alternateunits as alternate_units_id,
        alternateunitstype as alternate_units_type_id,
        amortizationenddate as amortization_end_date,
        amortizationschedule as amortization_schedule_id,
        amortizationstartdate as amortization_start_date,
        amortizationtemplate as amortization_template_id,
        fairvalue as fair_value,
        calculatedamount as calculated_amount,
        carveinratio as carve_in_ratio,
        carveoutratio as carve_out_ratio,
        class as class_id,
        contractcostallocationpct as contract_cost_allocation_percentage,
        contractexpenseacct as contract_expense_account_id,
        contractexpenseoffsetacct as contract_expense_offset_account_id,
        costamortizationamount as cost_amortization_amount,
        createrevenueplanson as create_revenue_plans_on_id,
        {% if var('netsuite__multiple_currencies_enabled', false) %}
        currency as currency_id,
        exchangerate as exchange_rate,
        revreclassfxaccount as foreign_currency_adjustment_account_id,
        {% endif %}
        entity as entity_id,
        deferralaccount as deferral_account_id,
        defercontractexpenseacct as defer_contract_expense_account_id,
        journalentry as journal_entry_id,
        delivered = 'T' as is_delivered,
        department as department_id,
        discountedsalesamount as discounted_sales_amount,
        effectiveenddate as effective_end_date,
        effectivestartdate as effective_start_date,
        contingentrevenuehandling = 'T' as is_contingent_revenue_handling,
        revrecenddate as rev_rec_end_date,
        treatmentoverride = 'T' as is_treatment_override,
        expensemigrateadjaccount as expense_migration_adjustment_account_id,
        externalid as external_id,
        fairvalueoverride = 'T' as is_fair_value_override,
        forecastenddate as forecast_end_date,
        forecaststartdate as forecast_start_date,
        fullname as revenue_element_full_name,
        id as revenue_element_id,
        isbomitemtype = 'T' as is_bom_item_type,
        isvsoeprice = 'T' as is_vsoe_price,
        item as item_id,
        itemlaborcostamount as item_labor_cost_amount,
        itemresalecostamount as item_resale_cost_amount,
        labordeferredexpenseacct as labor_deferred_expense_account_id,
        laborexpenseacct as labor_expense_account_id,
        lastmergedfromarrangement as last_merged_from_arrangement,
        lastmodifieddate as last_modified_date,
        returnofelement as return_of_element_id,
        location as location_id,
        recordnumber as record_number,
        originalchangeorderdiscamount as original_discounted_sales_amount,
        originalchangeorderquantity as original_quantity,
        carveoverride = 'T' as is_carve_override,
        parentbomelement as parent_bom_element_id,
        permitdiscount = 'T' as is_permit_discount,
        postingdiscountapplied = 'T' as is_posting_discount_applied,
        quantity,
        recognitionaccount as recognition_account_id,
        recognitiontreatment as recognition_treatment_id,
        referenceid as reference_id,
        requiresrevenueplanupdate = 'T' as is_requires_revenue_plan_update,
        residualdiscsalesamount as residual_discounted_sales_amount,
        revenueallocationgroup as revenue_allocation_group_id,
        revenueallocationratio as revenue_allocation_ratio,
        allocationamount as allocation_amount,
        revenuearrangement as revenue_arrangement_id,
        revenuemigrateadjaccount as revenue_migration_adjustment_account_id,
        revenueplanstatus as revenue_plan_status_id,
        revenuerecognitionrule as revenue_recognition_rule_id,
        revrecforecastrule as revenue_recognition_forecast_rule_id,
        salesamount as sales_amount,
        source,
        elementdate as element_date,
        revrecstartdate as rev_rec_start_date,
        subscriptionline as subscription_line,
        subsidiary as subsidiary_id,
        carveinamount as carve_in_amount,
        carveoutamount as carve_out_amount,
        termindays as term_in_days,
        terminmonths as term_in_months,
        newstandardmigratedate as new_standard_migrate_date,
        unbilledreceivablegroup as unbilled_receivable_group,
        units,
        _swishbi_id,
        _change_type,
        _commit_version,
        _commit_timestamp

    from source
)
select * from renamed
  