{{ config(enabled=(var('netsuite__advanced_revenue_management_enabled', false))) }}

with source as (
      select * from {{ source('netsuite', 'revenueelement') }}
),
renamed as (
    select
        {{ adapter.quote("itemisautoexpand") }} as is_item_auto_expand,
        {{ adapter.quote("sourcerecordtype") }} as source_record_type,
        {{ adapter.quote("accountingbook") }} as accounting_book_id,
        {{ adapter.quote("cseg_paactivitycode") }} as activity_code,
        {{ adapter.quote("allocatedcontractcostamount") }} as allocated_contract_cost_amount,
        {{ adapter.quote("allocationtype") }} as allocation_type_id,
        {{ adapter.quote("alternatequantity") }} as alternate_quantity,
        {{ adapter.quote("alternateunits") }} as alternate_units_id,
        {{ adapter.quote("alternateunitstype") }} as alternate_units_type_id,
        {{ adapter.quote("amortizationenddate") }} as amortization_end_date,
        {{ adapter.quote("amortizationschedule") }} as amortization_schedule_id,
        {{ adapter.quote("amortizationstartdate") }} as amortization_start_date,
        {{ adapter.quote("amortizationtemplate") }} as amortization_template_id,
        {{ adapter.quote("fairvalue") }} as fair_value,
        {{ adapter.quote("calculatedamount") }} as calculated_amount,
        {{ adapter.quote("carveinratio") }} as carve_in_ratio,
        {{ adapter.quote("carveoutratio") }} as carve_out_ratio,
        {{ adapter.quote("class") }} as class_id,
        {{ adapter.quote("contractcostallocationpct") }} as contract_cost_allocation_percentage,
        {{ adapter.quote("contractexpenseacct") }} as contract_expense_account_id,
        {{ adapter.quote("contractexpenseoffsetacct") }} as contract_expense_offset_account_id,
        {{ adapter.quote("costamortizationamount") }} as cost_amortization_amount,
        {{ adapter.quote("createrevenueplanson") }} as create_revenue_plans_on_id,
        {{ adapter.quote("currency") }} as currency_id,
        {{ adapter.quote("entity") }} as entity_id,
        {{ adapter.quote("deferralaccount") }} as deferral_account_id,
        {{ adapter.quote("defercontractexpenseacct") }} as defer_contract_expense_account_id,
        {{ adapter.quote("journalentry") }} as journal_entry_id,
        {{ adapter.quote("delivered") }} as is_delivered,
        {{ adapter.quote("department") }} as department_id,
        {{ adapter.quote("discountedsalesamount") }} as discounted_sales_amount,
        {{ adapter.quote("effectiveenddate") }} as effective_end_date,
        {{ adapter.quote("effectivestartdate") }} as effective_start_date,
        {{ adapter.quote("contingentrevenuehandling") }} as is_contingent_revenue_handling,
        {{ adapter.quote("revrecenddate") }} as rev_rec_end_date,
        {{ adapter.quote("exchangerate") }} as exchange_rate,
        {{ adapter.quote("treatmentoverride") }} as is_treatment_override,
        {{ adapter.quote("expensemigrateadjaccount") }} as expense_migration_adjustment_account_id,
        {{ adapter.quote("externalid") }} as external_id,
        {{ adapter.quote("fairvalueoverride") }} as is_fair_value_override,
        {{ adapter.quote("forecastenddate") }} as forecast_end_date,
        {{ adapter.quote("forecaststartdate") }} as forecast_start_date,
        {{ adapter.quote("revreclassfxaccount") }} as foreign_currency_adjustment_account_id,
        {{ adapter.quote("fullname") }} as revenue_element_full_name,
        {{ adapter.quote("id") }} as revenue_element_id,
        {{ adapter.quote("isbomitemtype") }} as is_bom_item_type,
        {{ adapter.quote("isvsoeprice") }} as is_vsoe_price,
        {{ adapter.quote("item") }} as item_id,
        {{ adapter.quote("itemlaborcostamount") }} as item_labor_cost_amount,
        {{ adapter.quote("itemresalecostamount") }} as item_resale_cost_amount,
        {{ adapter.quote("labordeferredexpenseacct") }} as labor_deferred_expense_account_id,
        {{ adapter.quote("laborexpenseacct") }} as labor_expense_account_id,
        {{ adapter.quote("lastmergedfromarrangement") }} as last_merged_from_arrangement,
        {{ adapter.quote("lastmodifieddate") }} as last_modified_date,
        {{ adapter.quote("returnofelement") }} as return_of_element_id,
        {{ adapter.quote("location") }} as location_id,
        {{ adapter.quote("recordnumber") }} as record_number,
        {{ adapter.quote("originalchangeorderdiscamount") }} as original_discounted_sales_amount,
        {{ adapter.quote("originalchangeorderquantity") }} as original_quantity,
        {{ adapter.quote("carveoverride") }} as is_carve_override,
        {{ adapter.quote("parentbomelement") }} as parent_bom_element_id,
        {{ adapter.quote("permitdiscount") }} as is_permit_discount,
        {{ adapter.quote("postingdiscountapplied") }} as is_posting_discount_applied,
        {{ adapter.quote("quantity") }},
        {{ adapter.quote("recognitionaccount") }} as recognition_account_id,
        {{ adapter.quote("recognitiontreatment") }} as recognition_treatment_id,
        {{ adapter.quote("referenceid") }} as reference_id,
        {{ adapter.quote("requiresrevenueplanupdate") }} as is_requires_revenue_plan_update,
        {{ adapter.quote("residualdiscsalesamount") }} as residual_discounted_sales_amount,
        {{ adapter.quote("revenueallocationgroup") }} as revenue_allocation_group_id,
        {{ adapter.quote("revenueallocationratio") }} as revenue_allocation_ratio,
        {{ adapter.quote("allocationamount") }} as allocation_amount,
        {{ adapter.quote("revenuearrangement") }} as revenue_arrangement_id,
        {{ adapter.quote("revenuemigrateadjaccount") }} as revenue_migration_adjustment_account_id,
        {{ adapter.quote("revenueplanstatus") }} as revenue_plan_status_id,
        {{ adapter.quote("revenuerecognitionrule") }} as revenue_recognition_rule_id,
        {{ adapter.quote("revrecforecastrule") }} as revenue_recognition_forecast_rule_id,
        {{ adapter.quote("salesamount") }} as sales_amount,
        {{ adapter.quote("source") }},
        {{ adapter.quote("elementdate") }} as element_date,
        {{ adapter.quote("revrecstartdate") }} as rev_rec_start_date,
        {{ adapter.quote("subscriptionline") }} as subscription_line,
        {{ adapter.quote("subsidiary") }} as subsidiary_id,
        {{ adapter.quote("carveinamount") }} as carve_in_amount,
        {{ adapter.quote("carveoutamount") }} as carve_out_amount,
        {{ adapter.quote("termindays") }} as term_in_days,
        {{ adapter.quote("terminmonths") }} as term_in_months,
        {{ adapter.quote("newstandardmigratedate") }} as new_standard_migrate_date,
        {{ adapter.quote("unbilledreceivablegroup") }} as unbilled_receivable_group,
        {{ adapter.quote("units") }},
        {{ adapter.quote("_swishbi_id") }},
        {{ adapter.quote("_change_type") }},
        {{ adapter.quote("_commit_version") }},
        {{ adapter.quote("_commit_timestamp") }}

    from source
)
select * from renamed
  